version: '3'

networks:
  laravel-gossip:

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: lg-mysql
    tmpfs: /var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel-gossip

  php:
    image: owow/laravel-php:8.1
    container_name: lg-php
    tty: true
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel-gossip
