version: '3'

networks:
  laravel-gossip:

services:
  mysql:
    image: mysql:5.7
    container_name: lg-mysql
    tmpfs: /var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
    networks:
      - laravel-gossip

  php:
    image: thomasowow/laravel-php:7.4
    container_name: lg-php
    tty: true
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel-gossip
